#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : tenacity
Version  : 4.1.0
Release  : 1
URL      : https://pypi.python.org/packages/42/e7/1b5acde23073873a3f463ed4da538e7457113d1e2ff58256fc6bf18bc72b/tenacity-4.1.0.tar.gz
Source0  : https://pypi.python.org/packages/42/e7/1b5acde23073873a3f463ed4da538e7457113d1e2ff58256fc6bf18bc72b/tenacity-4.1.0.tar.gz
Summary  : Retry code until it succeeeds
Group    : Development/Tools
License  : Apache-2.0
Requires: tenacity-python
Requires: futures
Requires: monotonic
Requires: six
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools

%description
Tenacity
========
.. image:: https://img.shields.io/pypi/v/tenacity.svg
:target: https://pypi.python.org/pypi/tenacity

%package python
Summary: python components for the tenacity package.
Group: Default

%description python
python components for the tenacity package.


%prep
%setup -q -n tenacity-4.1.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1494444452
python2 setup.py build -b py2
python3 setup.py build -b py3

%install
export SOURCE_DATE_EPOCH=1494444452
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot} --force
python3 -tt setup.py build -b py3 install --root=%{buildroot} --force
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)
/usr/lib/python2*/*
/usr/lib/python3*/*
